/*
 * generated by Xtext 2.26.0
 */
package org.example.domainmodel.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.nilostep.urm.dsl.ui.internal.DslActivator;

public class DomainmodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.example.domainmodel.Domainmodel");
	}

}
